[package]
authors = ["Xavier Lau <c.estlavie@icloud.com>"]
edition = "2018"
name    = "grandma"
version = "0.2.0"

[dependencies]
array-bytes        = { version = "0.3.0" }
clap               = { version = "3.0.0-beta.2" }
colored            = { version = "2.0.0" }
parity-scale-codec = { version = "1.3.5", features = ["derive"] }
serde              = { version = "1.0.118", features = ["derive"] }
serde_json         = { version = "1.0.61" }
subcryptor         = { version = "0.1.0" }
subgrandpa         = { version = "0.2.0", features = ["codec"] }
subrpcer           = { version = "0.1.2" }
substorager        = { version = "0.1.0" }
tungstenite        = { version = "0.11.1" }
