[package]
authors = ["Xavier Lau <c.estlavie@icloud.com>"]
edition = "2018"
name    = "grandma"
version = "0.1.0"

[dependencies]
base58             = { version = "0.1.0" }
blake2-rfc         = { version = "0.2.18" }
byteorder          = { version = "1.3.4" }
clap               = { version = "3.0.0-beta.2" }
colored            = { version = "2.0.0" }
parity-scale-codec = { version = "1.3.5", features = ["derive"] }
serde              = { version = "1.0.117", features = ["derive"] }
serde_json         = { version = "1.0.59" }
tungstenite        = { version = "0.11.1" }
twox-hash          = { version = "1.6.0" }
